% function [predicted_labels decision_values] = correlation_classifier(labels_test,data_test,model)
%
% This function uses a Haxby style MVPA analysis where multivoxel patterns
% *within* one class are simply correlated and tested against another 
% correlation *between* the same and a different classes. The pattern is 
% said to carry information about the category if the within class 
% correlation is higher than the between class correlation. The output 
% predicted_labels is the prediction that is generated by the higher 
% correlation coefficient. The output decision_values is the z_transformed 
% correlation difference generated by the within and between correlation 
% comparison.
%
% For more than two classes, the highest correlation receives the class
% label. In other words, there is no difference between a one-vs-one and 
% one-vs-all classifier.
%
% 2009 Martin H.

% History:
% 2014-01-19 Martin:
% - made compatible with multiple classes

% Typical structure of MVPA:
% 1. Split-half of two data sets (in general split n possible)
% 2. First half of label 1 correlated with second half of label 1, 
%    first half of label 2 correlated with second half of label 2
% 3. First half of label 1 correlated with second half of label 2,
%    first half of label 2 correlated with second half of label 1
% 4. Comparison of these two correlations
% 5. Possibly classification: For which label is the correlation higher?

function [predicted_labels decision_values] = correlation_classifier(labels_test,data_test,model)

% It is possible that a test label does not match the training labels, but
% this function should still be able to deal with this case. In that case,
% a test label could not be predicted correctly, but that should also be
% known to the programmer. It would be more about cross-classification in
% that case.

% Bear in mind that this gives us an incomplete pairing for training and test (and thus empty
% entries in a nxn matrix if such a matrix is desired)
% Another issue: if training labels are 1, 2, 3, and test labels are 1, and
% 3, then the order is unclear. We need to report whether columns are
% training or rows, and vice versa for test (is test rows or columns)
% only then a unique solution is possible
%
% Also remember that the labels are sorted according to their number, so -1
% is first and 1 is second (etc.)
%
%
% For computation, try out the following examples:
% Only 2 labels as usual
% Three labels each
% Three training labels, two test labels, also with only one voxel
% Two training labels, three test labels

% unpack
data_train = model.data_train;
labels_train = model.labels_train;

unique_labels_train = uniqueq(labels_train); % this also sorts labels
unique_labels_test = uniqueq(labels_test); % this also sorts labels

n_labels_train = size(unique_labels_train,1);
n_labels_test = size(unique_labels_test,1);
[n_samples_train,n_vox] = size(data_train);
n_samples_test = size(data_test,1);

% If multiple instances of training and test vectors are present, combine
% them together (create a different classifier if you want to keep them
% separate)
train = zeros(n_vox,n_labels_train);
for i_label = 1:n_labels_train
    train(:,i_label) = sum(data_train(labels_train==unique_labels_train(i_label),:),1);
end
test = zeros(n_vox,n_labels_test);
for i_label = 1:n_labels_test
    test(:,i_label) = sum(data_test(labels_test==unique_labels_test(i_label),:),1);
end

if n_samples_train ~= n_samples_test % only in this case we need to normalize
    train = train/n_samples_train;
    test = test/n_samples_test;
end
    
if n_vox > 1 % normal case in which more than one voxel is present
    
    % create correlation matrix
    r = correlmat(train,test);
    
    % force finite values for later z-transformation
    r1 = abs(r)==1;
    if any(r1(:))
        warning('CORRELATION_CLASSIFIER:ZCORRINF','Correlations of +1 or -1 found. Correcting to +/-0.99999 to avoid infinity for z-transformed correlations!')
        r(r1) = 0.99999*r(r1); % forces finite values
    end
    
    % translate to Fisher's z transformed values for decision-values
    z = atanh(r);

    % these are not the same as decision values, but they give a useful distance metric from the classification boundary
    % TODO: find out how decision values are reported from libsvm in a multiclass scenario and apply the same scenario here
    [decision_values,predict_ind] = max(z); % = [zcorr_within(1,1)-zcorr_between(1,1); -(zcorr_within(2,1)-zcorr_between(2,1))];
    predicted_labels = unique_labels_test(predict_ind);


else % if only one voxel is present, a correlation is not possible
   
warning('CORRELATION_CLASSIFIER:ONEVOXEL','Searchlight or ROI with only one voxel (may happen at borders of mask). No correlation possible, setting value to NaN!')

r = NaN(n_labels_train,n_labels_test);
z = NaN(n_labels_train,n_labels_test);
decision_values = NaN(n_labels_test,1);
predicted_labels = NaN(n_labels_test,1);

end


% function ind = uniqueq(x,sortedflag)
% 
% Much faster than unique, and even faster when indices are already sorted
% (when any second input is provided). Assumes a vector of indices.

function ind = uniqueq(x,sortedflag)

if nargin == 1
    x = sort(x); 
end

ind = x([true; diff(x)>0]);