% function [predicted_labels decision_values] = correlation_classifier(labels_test,vectors_test,model)
%
% This function uses a Haxby style MVPA analysis where multivoxel patterns
% *within* one class are simply correlated and tested against another 
% correlation *between* the same and a different classes. The pattern is 
% said to carry  information about the category if the within class 
% correlation is higher than the between class correlation. The output 
% predicted_labels is the prediction that is generated by the higher 
% correlation coefficient. The output decision_values is the z_transformed 
% correlation difference generated by the within and between correlation 
% comparison.

% Typical structure of MVPA:
% 1. Split-half of two data sets (in general split n possible)
% 2. First half of label 1 correlated with second half of label 1, 
%    first half of label 2 correlated with second half of label 2
% 3. First half of label 1 correlated with second half of label 2,
%    first half of label 2 correlated with second half of label 1
% 4. Comparison of these two correlations
% 5. Possibly classification: For which label is the correlation higher?

function [predicted_labels decision_values] = correlation_classifier(labels_test,vectors_test,model)

[labels,tmp,labels_ind] = unique(labels_test);

n_labels = size(labels,1);

if n_labels ~= 2, error('Correlation classifier cannot yet deal with more than two labels at a time.\n Run all pairs separately.'), end

vectors_train = model.vectors_train;
labels_train = model.labels_train;

% create training and test vectors
train = cell(n_labels,1);
test = cell(n_labels,1);
for i_label = 1:n_labels
    % TODO: possibly replace mean by % sum(...,1)/sum(labels_train==i_label) to gain speed
    train{i_label} = mean(vectors_train(labels_train==labels(i_label),:),1);
    test{i_label} = mean(vectors_test(labels_test==labels(i_label),:),1);
end

if numel(train{1,1}>1) % normal case in which more than one voxel is present
    
corr_within(1,1) = correl(train{1},test{1});
corr_within(2,1) = correl(train{2},test{2});
corr_between(1,1) = correl(train{1},test{2});
corr_between(2,1) = correl(train{2},test{1});

else % if only one voxel is present, a correlation is not possible
   
warning('CORRELATION_CLASSIFIER:ONEVOXEL','Searchlight or ROI with only one voxel (may happen at borders of mask). Using nearest absolute neighbor instead of correlation!')
% Instead choose predicted labels based on distance, normalized across all
% and with very small absolute values to reduce the size of the effect, but 
% still yield interpretable results in terms of predicted_labels.
maxval = max([train{1}(:); test{1}(:); train{2}(:); test{2}(:)].^2);
corr_within(1,1) = 0.001 * (train{1}-test{1}).^2/maxval;
corr_within(2,1) = 0.001 * (train{2}-test{2}).^2/maxval;
corr_between(1,1) = 0.001 * (train{1}-test{2}).^2/maxval;
corr_between(2,1) = 0.001 * (train{1}-test{2}).^2/maxval;
    
end

% accuracy = mean(zcorr_within > zcorr_between); % not needed here, but leave me here in case

% force finite values for later z-transformation
if any(abs(corr_within==1))
warning('CORRELATION_CLASSIFIER:ZCORRINF','Correlations of +1 or -1 found. Correcting to +/-0.99999 to avoid infinity for z-transformed correlations!')
corr_within(corr_within==1) = 0.99999; % forces finite values
corr_within(corr_within==-1) = -0.99999; % forces finite values
corr_between(corr_between==1) = 0.99999; % forces finite values
corr_between(corr_between==-1) = -0.99999; % forces finite values
end

% translate to Fisher's z transformed values
zcorr_within = atanh(corr_within);
zcorr_between = atanh(corr_between);

% this is not the same as decision values, but we just call it so to keep the variable structure
decision_values = [zcorr_within(1,1)-zcorr_between(1,1); -(zcorr_within(2,1)-zcorr_between(2,1))];
predicted_labels(decision_values > 0, 1) = labels(1);
predicted_labels(decision_values <= 0, 1) = labels(2);

predicted_labels = predicted_labels(labels_ind);

