display(['For the moment, see demos in prevalenceInference directory ' char(10) ...
    '(maybe called prevalenceInference_beta1) ' char(10) ...
    'on how to use the prevalence inference analysis'])